use BDSISTR
CREATE TABLE usuario (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL,
    CONTRASEÑA VARCHAR(8) NOT NULL);

INSERT INTO usuario (USUARIO, CONTRASEÑA)
VALUES ('usuario1', '12345678')

SELECT * FROM ESTUDIANTE