USE BDSISTR
create proc INSERTAR 
@ID int,
@PRIMER_NOMBRE VARCHAR (50),
@SEGUNDO_NOMBRE VARCHAR (50),
@PRIMER_APELLIDO VARCHAR (50),
@SEGUNDO_APELLIDO VARCHAR (50),
@NIVEL VARCHAR (50),
@GRADO VARCHAR (20),
@SECCIÓN VARCHAR (3),
@SEXO VARCHAR (15),
@DNI VARCHAR (8),
@TELÉFONO VARCHAR (9),
@DIRECCIÓN VARCHAR (60),
@NACIMIENTO DATE,
@OBSERVACIONES VARCHAR(100)
AS 
INSERT INTO Estudiante VALUES (@ID,@PRIMER_NOMBRE, @SEGUNDO_NOMBRE,@PRIMER_APELLIDO, @SEGUNDO_APELLIDO, @NIVEL, @GRADO, @SECCIÓN, @SEXO, @DNI, @TELÉFONO, @DIRECCIÓN, @NACIMIENTO, @OBSERVACIONES)
GO
select * from estudiante
ALTER TABLE Estudiante
ALTER COLUMN ID INT;
SELECT 
    c.name AS 'ID',
    t.name AS 'int',
    c.is_identity AS 'Es Identidad'
FROM sys.columns c
INNER JOIN sys.tables t ON c.object_id = t.object_id
WHERE 
    t.name = 'Estudiante' AND -- Reemplaza 'mi_tabla' con el nombre de tu tabla
    c.name = 'ID';
INSERT 
drop table Estudiante
CREATE TABLE Estudiante (
    ID INT PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
	SEGUNDO_APELLIDO VARCHAR(50),
    NIVEL VARCHAR(50),
    GRADO VARCHAR(20),
    SECCIÓN VARCHAR(3),
    SEXO VARCHAR(15),
    DNI VARCHAR(8),
    TELÉFONO VARCHAR(9),
    DIRECCIÓN VARCHAR(60),
    NACIMIENTO DATE,
    OBSERVACIONES VARCHAR(100)
);
DROP PROCEDURE INSERTAR;
DROP PROCEDURE Mostrar;
CREATE PROC MOSTRAR
AS 