USE BDSISTR
create proc INSERTAR 
@ID int,
@PRIMER_NOMBRE VARCHAR (50),
@SEGUNDO_NOMBRE VARCHAR (50),
@PRIMER_APELLIDO VARCHAR (50),
@NIVEL VARCHAR (50),
@GRADO VARCHAR (20),
@SECCIÓN VARCHAR (3),
@SEXO VARCHAR (15),
@DNI VARCHAR (8),
@TELÉFONO VARCHAR (9),
@DIRECCIÓN VARCHAR (60),
@NACIMIENTO DATE,
@OBSERVACIONES VARCHAR(100)
AS 
INSERT INTO Estudiante VALUES (@ID,@PRIMER_NOMBRE, @SEGUNDO_NOMBRE,@PRIMER_APELLIDO, @NIVEL, @GRADO, @SECCIÓN, @SEXO, @DNI, @TELÉFONO, @DIRECCIÓN, @NACIMIENTO, @OBSERVACIONES)
GO